# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sven', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('type', models.CharField(choices=[(b'fr', b'tags'), (b'tm', b'type_of_media'), (b'ac', b'actor'), (b'in', b'institution'), (b'pl', b'place'), (b'OP', b'oembed_provider_name'), (b'OT', b'oembed_title'), (b'OU', b'oembed_url'), (b'OH', b'oembed_thumbnail_url'), (b'OI', b'oembed_video_id'), (b'Oh', b'oembed_height'), (b'Ow', b'oembed_width')], default=b'fr', max_length=2)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sven.Corpus')),
            ],
        ),
    ]
